using System;
using System.IO;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;

namespace BlazorEngine.BuildTasks;

/// <summary>
///   MSBuild task that generates a C# file containing a [ModuleInitializer] method.
///   When the consuming assembly loads, the initializer automatically registers its
///   embedded metadata with BlazorEngine's MetadataRegistry — zero configuration required.
/// </summary>
public class GenerateModuleInitializerTask : Task
{
  [Required] public string OutputPath { get; set; } = "";

  /// <summary>
  ///   The assembly name used to locate the embedded resource.
  /// </summary>
  [Required]
  public string AssemblyName { get; set; } = "";

  /// <summary>
  ///   Path to the metadata .dat file. If it doesn't exist, we still
  ///   generate the initializer so it can register the assembly for
  ///   reflection fallback.
  /// </summary>
  [Required]
  public string MetadataFilePath { get; set; } = "";

  public override bool Execute()
  {
    try
    {
      var dir = Path.GetDirectoryName(OutputPath);
      if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
        Directory.CreateDirectory(dir);

      var hasMetadata = File.Exists(MetadataFilePath) && new FileInfo(MetadataFilePath).Length > 0;

      var code = GenerateCode(hasMetadata);

      // Only write if content changed (avoid unnecessary recompilation)
      if (File.Exists(OutputPath))
      {
        var existing = File.ReadAllText(OutputPath);
        if (existing == code)
        {
          Log.LogMessage(MessageImportance.Low, "BlazorEngine: Module initializer unchanged, skipping write.");
          return true;
        }
      }

      File.WriteAllText(OutputPath, code);
      Log.LogMessage(MessageImportance.Low,
        "BlazorEngine: Generated module initializer for '{0}' (metadata: {1}).",
        AssemblyName, hasMetadata ? "embedded" : "fallback");

      return true;
    }
    catch (Exception ex)
    {
      Log.LogWarning("BlazorEngine: Failed to generate module initializer: {0}", ex.Message);
      return true; // Degrade gracefully
    }
  }

  private string GenerateCode(bool hasMetadata)
  {
    var resourceName = AssemblyName + ".blazorengine.dat";

    return $@"// <auto-generated>
// This file is generated by BlazorEngine.BuildTasks at compile time.
// Do not modify. Changes will be overwritten on next build.
// </auto-generated>

using System.Runtime.CompilerServices;

namespace BlazorEngine.Generated
{{
  internal static class BlazorEngineModuleInit
  {{
    [ModuleInitializer]
    internal static void Register()
    {{
      var assembly = typeof(BlazorEngineModuleInit).Assembly;
{(hasMetadata ? $@"
      // Load pre-computed metadata from embedded resource (zero reflection)
      var stream = assembly.GetManifestResourceStream(""{resourceName}"");
      if (stream != null)
      {{
        BlazorEngine.Services.MetadataRegistry.RegisterFromStream(assembly, stream);
        return;
      }}
" : "")}
      // Register assembly for reflection fallback
      BlazorEngine.Services.MetadataRegistry.RegisterAssemblyForFallback(assembly);
    }}
  }}
}}
";
  }
}